### PR TITLE
Fix/add geography schema to policy

### PR DESCRIPTION
**Pull request by janedotx**
Addresses https://github.com/openmobilityfoundation/mobility-data-specification/issues/433#issuecomment-647856608

### CODE REVIEW

**Comment by schnuerle** [comment]
Thanks @janedotx.  Can you code the 2 timestamps as [timestamp][ts] so they can match the rest of the page and link to the timestamp explanation?

**Comment by janedotx** [comment]
> Thanks @janedotx. Can you code the 2 timestamps as [timestamp][ts] so they can match the rest of the page and link to the timestamp explanation?

Done!

**Comment by schnuerle** [comment]
Thanks Jane I was writing up a few more updates please!

- Remove the "<a name="geography-fields"></a>" above the table.
- Add a link to the Geography section in the geographies endpoint section, just like with Polices (eg, data Payload: { "policies": [] }, an array of objects with the structure outlined below.)
- R/O spelled out to Required/Optional like in the other tables, with R and O spelled out for each row too.
- move the Geography section up to go between Rule Units and Messages .

**Comment by janedotx** [comment]
@schnuerle I updated the `dev` branch of `lacuna-tech` to match the `dev`. Not sure why there's still a conflict in there. I think I've addressed all the other changes you requested.

**Comment by schnuerle** [comment]
Thanks Jane, all looks good barring one missed change: spell out the words Required and Optional in the table instead of R and O.

**Comment by schnuerle** [comment]
Also @janedotx are you sure you pulled the latest dev to your branch (not just the Lacuna dev branch)?  There are lots of changes between the OMF dev branch and the file in your PR.

**Comment by janedotx** [comment]
> Also @janedotx are you sure you pulled the latest dev to your branch (not just the Lacuna dev branch)? There are lots of changes between the OMF dev branch and the file in your PR.

I thought I'd gotten our branch in sync, but apparently not. Trying to figure it out now.

**Comment by janedotx** [comment]
> > Also @janedotx are you sure you pulled the latest dev to your branch (not just the Lacuna dev branch)? There are lots of changes between the OMF dev branch and the file in your PR.
> 
> I thought I'd gotten our branch in sync, but apparently not. Trying to figure it out now.

@schnuerle I think things are okay now.

**Pull request merged**
