### PR TITLE
Add membership type field

### PR DESCRIPTION
**Pull request by cttengsfmta**
Add membership type field to the provider API. We presume that more values could be added to the list of membership types. (Reopening #106, as requested)

### CODE REVIEW

**Comment by hunterowens** [comment]
@cttengsfmta this looks good. We will also want to change the corresponding `JSONSchema` definitions for our [validator](https://github.com/CityOfLosAngeles/mds-validator) codebases. Do you want to take a crack at that or should I?

**Comment by hunterowens** [comment]
I wonder how similar #126 and #76 are.

**Comment by cttengsfmta** [comment]
I don't see a way to add a new Enum in `generate_provider_schema.py`

**Comment by alexdemisch** [comment]
To summarize the discussion from the 4/11 call, the current proposal would be to add the membership_type field, starting with the enum values proposed earlier.  This would be an optional field.  While this field does provide information related to the user of the trip, it is still generalized and not PII.  There are concerns that an enumerated list of values may not be able to capture quickly changing business models that may introduce new membership types, so the enum values would need to be actively managed.  An experimental prefix (e.g., “ex-“) could be used to allow new values not explicitly added to the list of enumerated values.

**Comment by lionel-panhaleux** [comment]
To summarize discussion from 4/18 :
- The specification states that a specific `Content-Type` should be used for responses, cf. https://github.com/CityOfLosAngeles/mobility-data-specification/tree/dev/provider#versioning

This means an `OPTIONS` request can be used for version negociation using the `Accept` header, cf. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept . Example: 

Ask for options, stating that version 0.2 is preferred to version 0.3 (using the q parameter):
```
OPTIONS /trips/ HTTP/1.1 
Host: provider.example.com 
Accept: application/vnd.mds.provider+json;version=0.2,application/vnd.mds.provider+json;version=0.3;q=0.9
```

Answer: Only version 0.3 available
```
HTTP/1.1 200 OK
Content-Type: mds.provider+json;version=0.3
```

**Comment by hunterowens** [comment]
moving this to 0.4.1 as an optional field.

**Comment by hunterowens** [comment]
@dirkdk to rewrite based on discussion on 1/16 into a separate reporting / equity notes.

**Comment by schnuerle** [comment]
Would like to revisit this idea for adding this info directly to the Provider API, in addition to potentially adding to a Metrics API #486.

**Comment by schnuerle** [comment]
This is being discussed as part of a subset of a proposed Metrics API with aggregated (not trip level) information about special groups in #569.

**Comment by johnclary** [comment]
I'm strongly opposed to adding attributes to trip records that describe the users taking trips.

**Comment by alexdemisch** [comment]
We've discussed some of this already in some of the Provider WG calls on Metrics, but I'd consider this specific proposal to add additional elements to the detailed trip data to be abandoned in favor of the aggregate "special groups" reporting in the Metrics #569.  

The only reason it would've be collected at a detailed level would be to roll it up anyway, so #569 is a better way to do this.

**Comment by schnuerle** [comment]
Closing this in favor of work on #569.

**Pull request closed without merging**
