### PR TITLE
Add TukTuk provider

### PR DESCRIPTION
**Pull request by schnuerle**
Add TukTuk as a provider

### CODE REVIEW

**Comment by drtyh2o** [comment]
@schnuerle I think this PR should have been merged to `dev` instead of `main`? Can you add it or is there a standard process/schedule for merging `dev` to `main`? Thanks!

**Comment by schnuerle** [comment]
> @schnuerle I think this PR should have been merged to `dev` instead of `main`? Can you add it or is there a standard process/schedule for merging `dev` to `main`? Thanks!

This PR did go to dev, do you see otherwise? https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv

There is no way in GitHub to set PRs in a repo to automatically go to a branch other than main. It's left up to the proposer. We do have a message in the PR default text that says to push to dev. Also as an admin if someone misses it, I can edit from main to dev if needed.

**Comment by drtyh2o** [comment]
> This PR did go to dev, do you see otherwise? https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv

@schnuerle My bad, I meant to say it should have been merged to `main` instead of `dev`. What's the process for getting changes into `main`?

**Comment by schnuerle** [comment]
That happens after the release is approved. So changes to main have happened with these releases and dates.
https://github.com/openmobilityfoundation/mobility-data-specification/releases

The IDs can still be used in production once they are in main, from the OMF perspective. 
https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Adding-an-MDS-Provider-ID#using-your-id

**Comment by schnuerle** [comment]
Don't forget to add your GBFS URL when it is ready. See this [requirement](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#GBFS).

**Pull request merged**
