### PR TITLE
Add MDS Audit Draft

### PR DESCRIPTION
**Pull request by whereissean**
### Explain pull request

Add new Audit API and associated schema for the evaluation of the technical compliance of providers.

### Is this a breaking change

A breaking change would require consumers or implementors of the API to modify their code for it to continue to function (ex: renaming of a required field or the change in data type of an existing field). A non-breaking change would allow existing code to continue to function (ex: addition of an optional field or the creation of a new optional endpoint). 

* [ ] Yes, breaking
* [x] No, not breaking
* [ ] I'm not sure

### `Provider` or `agency`

Which API(s) will this pull request impact:

* [ ] `provider`
* [ ] `agency`
* [ ] both
* [x] neither

### Additional context

MDS enables cities or municipal operators to receive information directly from regulated / permitted entities ("providers") relating to the behavior of vehicles and devices in the public right of way. During initial onboarding of providers and thereafter for maintenance purposes, it may be necessary for the city or its agents to attempt to audit or otherwise ensure that this information is correct.

This question of auditable compliance relates both to the correct formatting of data (e.g., no malformed inputs), its accuracy, and its timeliness. These three factors together are important contributors to the evaluation of the _technical compliance_ of a provider. This is to say, the compliance of regulated / permitted vehicles or devices with the specific requirements laid out both by MDS as a system of interfaces, and by the specific program terms or requirements (e.g. an event telemetry submission latency window, a telemetry temporal resolution requirement, and for the evaluation of the precision of such submissions consistent with GPS accuracy requirements or other program terms that may vary from city to city or within the scope of permitted and regulated program operations.

This specification defines an API which facilitates in-field data collection and evaluation of the technical compliance of providers. It is not intended as a substitute for other evaluative, cooperative, or corrective measures in the implementation or ongoing operations of MDS.

### CODE REVIEW

**Comment by hunterowens** [comment]
changing milestone for now.

**Comment by jfh01** [comment]
Should we consider for the 1.0.0 release?

**Comment by schnuerle** [comment]
HI @ drtyh2o can make sure to sign the [CLA](https://cla-assistant.io/openmobilityfoundation/mobility-data-specification?pullRequest=326) for your contribution?

**Comment by schnuerle** [comment]
This PR will be closed per our call today in favor of #483.

**Pull request closed without merging**
