### PR TITLE
Add stop references to trips and status_changes

### LINKED ISSUE #428: Modify /trips to represent docked start/end locations
### Is your feature request related to a problem? Please describe.

This Issue follows from the [Provider WG discussion on 2020/01/16](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2020.01.16-(Provider-Services-wg)) and the existing Issue #374 and related PR #427 related to bringing docked bikeshare support to MDS Provider.

### Describe the solution you'd like

The current `/trips` endpoint was envisioned with dockless micromobility in mind - specifically, trips have a geographic (lat/lng) start and end location. In the world of docked bikeshare/micromobility, we would rather represent the trip as starting/ending at a particular dock/stop.

### Is this a breaking change

* Yes, breaking

Likely breaking as we would be changing the `/trips` definition.

### Impacted Spec

* `provider`

### Describe alternatives you've considered

We want MDS to represent docked bikeshare true to the spirit of MDS - granular data useful in regulatory and planning contexts. While possible, simply encoding GBFS data into MDS endpoints/data types wouldn't represent a true evolution of the MDS spec.

### PR DESCRIPTION
**Pull request by avatarneil**
### Explain pull request
Resolves #428 following @jfh01's suggestion to use GeoJSON Foreign Members. Relates pretty closely to the open PR #427, and is dependent on that being merged first.

### Is this a breaking change

 * No, not breaking

### Impacted Spec

 * `provider`

### CODE REVIEW

**Comment by thekaveman** [comment]
Two comments:

1. I know @jfh01 suggested the use of Foreign Members, and I don't see a specific issue there. I just wonder if there is any reason not to extend our existing use of the `properties` object already present in GeoJSON Features?

2. Regardless of the answer to 1, the [schema](https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/schema/generate_schemas.py#L130) will need to be updated to handle the additional field.

**Comment by ascherkus** [comment]
Chiming in ... I'm also a bit hesitant on relying on GeoJSON foreign members vs. properties (similar to the hesitancy mentioned in #441).

Given:
  - The [GeoJSON spec cautions against it](https://tools.ietf.org/html/rfc7946#section-6.1)
  - We're already using `properties`
  - Other sources of GIS data seen in this space (notably GeoJSON produced from Shapefiles such as [Santa Moncia's drop zones](https://gis-smgov.opendata.arcgis.com/datasets/shared-mobility-drop-zones)) map attributes to properties

... I'm inclined to suggest sticking with `properties` for Feature-specific metadata, unless @jfh01 has some additional insight/experience into foreign members :)

Alternatively start/end stop ids could be expressed higher in the hierarchy alongside `start/end_time` -- the tradeoff there would being unable to express a trip that stopped at multiple stops (unclear to me if such a trip would exist, or if that would be represented as two trips with separate start/stop pairs). If I had to pick, I think sticking with Feature properties with schema validation accomplishes the same goal while retaining flexibility vs. adding more named fields at the top-level `trips` object.

**Comment by jfh01** [comment]
No particular insight here. I'm happy with either direction. Thanks!

**Comment by avatarneil** [comment]
Updated the PR to move the `stop` definitions to the top level of the`trips` and `status_changes` objects.

**Comment by thekaveman** [comment]
@rgangopadhya 

> Hmm, I do think this could be useful, though. I must've missed it on the call but did we agree to remove this?

I think we decided to move it nearer to the geometry, inside the `properties` object of relevant GeoJSON Feature (`status_change.event_location`, the first/last point in `trip.route`). This PR has been updated to reflect the changes for `trip.route` but it looks like we still need something for `status_changes.event_location` @avatarneil

**Comment by avatarneil** [comment]
Hi @thekaveman, I've updated the `event_location` definition. Sorry for the delay!

**Comment by thekaveman** [comment]
I rebased on the latest `dev` to incorporate Reconciliation changes. Let's wait to merge this after #427 so we can update references to Stops in the Provider README.

**Pull request merged**
