### PR TITLE
MDS-Agency Stops Specification

### PR DESCRIPTION
**Pull request by avatarneil**
### Explain pull request

This PR is a work in progress to reflect changes from #427 in MDS Agency .

### Is this a breaking change

 * I'm not sure

### Impacted Spec

 * `agency`

### CODE REVIEW

**Comment by Retzoh** [comment]
Why not have a single definition for stop payloads referenced by the agency and provider specs to make sure:
1.  They are compatible
2. We won't see a drift in content, requiring us to do a re conciliation sometime in the future
?

**Comment by avatarneil** [comment]
@Retzoh I'd be happy to move these changes over to the branch currently focused on the Provider changes, and merge the data definitions (though it probably won't get done by the City Services meeting today).

**Comment by Retzoh** [comment]
@avatarneil , let us ask this question during the city-services call today since docked is on the agenda

**Comment by schnuerle** [comment]
See discussion on Provider Stops PR #427: https://github.com/openmobilityfoundation/mobility-data-specification/pull/427#issuecomment-642866856

**Comment by avatarneil** [comment]
Closing in favor of #427 which consolidates both the agency & provider changes needed

**Pull request closed without merging**
