### PR TITLE
Adding GIG and their provider uuid

### PR DESCRIPTION
**Pull request by AssafRideCell**
---
name: Default
about: Suggest changes to MDS
title: <Insert Title>

---

# MDS Pull Request

Thank you for your contribution!  Please review our OMF [contributing page](https://github.com/openmobilityfoundation/governance/blob/main/CONTRIBUTING.md) to understand guidelines and policies for participation, and our [Code of Conduct page](https://github.com/openmobilityfoundation/governance/blob/main/CODE_OF_CONDUCT.md).

To avoid complications and help make the Review process as smooth as possible, make sure to:

1. Target [**`dev`**](https://github.com/openmobilityfoundation/mobility-data-specification/tree/dev) branch. Please ensure you are targeting **`dev`**, not **`main`**. 
1. Keep the *"Allow edits from maintainers"* button checked to help us resolve some issues for you.
1. Be ready to resolve any merge conflicts before we approve your Pull Request.
1. Have an up to date profile, per our Github [community profile](https://github.com/openmobilityfoundation/governance/blob/main/CONTRIBUTING.md#community-profile) guildance.

## Explain pull request

We in Ridecell are service providers for GIG and we never added their data officially to the MDS repo

## Is this a breaking change
* No, not breaking

## Impacted Spec

Which spec(s) will this pull request impact?
* `provider`

### CODE REVIEW

**Comment by schnuerle** [comment]
Thank you for your submission it looks good overall!  

When will the MDS url be live and return something, like an authorization warning or note?  

Can you make a minor change to 1) remove trailing spaces before the UUIS and MDS URL and 2) add a trailing comma where GBFS would go.  Eg:

`GIG,42475742-8618-4fc0-aa8f-3b3948b84b85,https://gigcarshare.com/,https://global.us.prod.svc.ridecell.io/reporting/api/mds,`

Also do you have a GBFS URL? It's not technically required here, but it is required as part of MDS, so if you have or will have one available you can add it now or later.

**Comment by AssafRideCell** [comment]
Hello @schnuerle thanks for the edit! This API has been live for a couple of months now supporting version 0.4.X of status_change and trips endpoints,  we are working on versioning now to also support version 1.0 

The API must have the required authorization token we provided for the city 
So it you make a call to https://global.us.prod.svc.ridecell.io/reporting/api/mds/trips?event_time=2020-08-05T17 
it will return a 401 with `incorrect authentication credentials" error 

if you call without the event_time it will return 400 with  "no event_time parameter was set"

feel free to hit that API 

we have yet to implemented the GFBP end point, I was not aware this is a requirement

**Comment by schnuerle** [comment]
Thank you for the clarifications!

I see the 401 error now with this link: https://global.us.prod.svc.ridecell.io/reporting/api/mds/trips/

Before I was just trying this and got a 404 error so wanted to make sure it was working: https://global.us.prod.svc.ridecell.io/reporting/api/mds/

Here is the note in the MDS spec about GBFS for Provider: https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#GBFS

If you think you may have a GBFS location ready in the next 2-3 weeks, we can keep this open until then and it will still make the next 1.1.0 release.  If it's going to be longer we can merge this to dev now, you can use the UUID, and you could come back later to add GBFS.

**Comment by AssafRideCell** [comment]
no problem 

we will probably not be able to finish it in the last couple of weeks are we mostly focusing on the versioning efforts. so let's merge this to dev and will add the GBFS to our development timeline

**Comment by schnuerle** [comment]
Ok, looks good thanks. Feel free to point to this file in dev and reference the UUID until it gets merged to main in a few weeks/months with the [1.1.0 release](https://github.com/openmobilityfoundation/governance/wiki/Release-1.1.0). Let us know when you get GBFS running.

**Review by schnuerle — APPROVED** [review]
Ready for dev merge.

**Pull request merged**
