### PR TITLE
rename general-information.md

### PR DESCRIPTION
**Pull request by sarob**
It was discussed in a past wg-ops meeting to change this file to be topic specific rather general

## Is this a breaking change

* No, not breaking

## Impacted Spec

N/A

## Additional context

documentation change

### CODE REVIEW

**Comment by thekaveman** [comment]
As a slight aside, I couldn't find the minutes for the wg-ops discussion for this change, am I missing something? Would you mind giving a little more context around the discussion?

The idea for the `general-information.md` file came out of discussion in a number of issues/PRs and calls, see: #422, #444, #447, #455. I'm wondering if the smaller group in wg-ops gives enough chance for public discussion to decisions like these? In particular, I feel there should at least be an Issue before a PR, to have a chance for broader input / async input for those that can't participate in calls (I would say the same for agency/policy/provider changes as well).

**Comment by jfh01** [comment]
This PR conflicts with #468, which extends `general_information.md` beyond just versioning. Agree with Kegan that this needs more discussion if we're going to pursue this change.

**Comment by sarob** [comment]
This must have come from a separate conversation concerning governance documentation since I cannot find the reference in the wg-ops meeting notes either. Definitely was not meant to be an end run around the working groups.

**Comment by schnuerle** [comment]
Closed, no longer relevant.

**Pull request closed without merging**
