### PR TITLE
Clarify policy rule min and max are inclusive

### PR DESCRIPTION
**Pull request by jiffyclub**
## Explain pull request

The policy docs don't say anywhere whether the minimum and maximum values specified on policy rules are to be interpreted as a closed or open interval (that is, whether the endpoints are included in the interval). Most real world policies seem to treat these min and maxes inclusively, e.g. parking for a max of 2 hours or a 70 MPG speed limit. You're not in violation until you go over those maximums. So this change clarifies that min and max values on policy rules are meant to define an inclusive (or closed) interval where values equal to the min and max match the rule.

## Is this a breaking change

* No, not breaking

## Impacted Spec

* `policy`

## Additional context

N/A

### CODE REVIEW

**Comment by jiffyclub** [comment]
Per discussion with @avatarneil on an [MDS working group call](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.08.12-(Joint-Working-Group)) we may want to make the treatment of min and max a user configurable option. For some policies, especially those governing continuous values, it can make it easier to express a policy if min/max are _excluded_ from the range (making an open or half-open) an interval.

**Comment by schnuerle** [comment]
Realize this clarification language could be part of 1.2.0. What do you think about how to make these a configurable option, or is this idea for a future release? 

Looks like there also may be a conflict with dev now to resolve.

**Comment by jiffyclub** [comment]
See #689 for an alternative approach that lets users specify how `minimum` and `maximum` should be handled.

**Comment by schnuerle** [comment]
Per our [working group meeting](https://github.com/openmobilityfoundation/mobility-data-specification/wiki/Web-conference-notes,-2021.09.09-(MDS-Working-Group)#action-items), PR #689 was selected as preferable to this solution. IF agreed, @jiffyclub you may close this PR.

**Comment by jiffyclub** [comment]
Closing in favor of #689.

**Pull request closed without merging**
